# Generated by Django 5.1.7 on 2025-03-13 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='live_demo',
            new_name='live_demo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 13, 2, 31, 25, 63879, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects/'),
            preserve_default=False,
        ),
    ]
