# Generated by Django 5.1.7 on 2025-03-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_live_demo_project_live_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('ai', 'AI / Machine Learning'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
