# Generated by Django 5.2 on 2025-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_project_options_alter_service_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyHeroText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_displayed", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
