# Generated by Django 5.1.7 on 2025-03-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, help_text='E.g. CEO, Freelancer', max_length=100),
        ),
    ]
